=== Chaotikum/chaotikum-logo/chaotikum-logo.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT chaotikum-logo (chiprompt,style?,script?)>
<!ELEMENT chiprompt      (chip)>
<!ELEMENT chip           (pins)>
<!ELEMENT pins           (pins-right,pins-left,pins-top,pins-bottom)>
<!ELEMENT pins-top       (pin*)>
<!ELEMENT pins-left      (pin*)>
<!ELEMENT pins-bottom    (pin*)>
<!ELEMENT pins-right     (pin*)>
<!ELEMENT pin            EMPTY>
<!ELEMENT script         (#PCDATA)>
<!ELEMENT style          (#PCDATA)>

<!ATTLIST chip width  CDATA "73.6">
<!ATTLIST pins
          pin-height  CDATA "13.2"
          pin-padding CDATA "8.3"
          pin-width   CDATA "6.7">
<!ATTLIST pin
          id          ID #IMPLIED
          class       CDATA #IMPLIED>
<!ATTLIST style type  CDATA "text/css">
<!ATTLIST script type CDATA "text/javascript">

=== Chaotikum/chaotikum-logo/animated/chip-prompt-secs-mod-20.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE chaotikum-logo SYSTEM "../chaotikum-logo.dtd">
<chaotikum-logo>
  <chiprompt>
    <chip>
      <pins>
        <pins-right>
          <pin id="pin04" class="pin04" />
          <pin id="pin03" class="pin03" />
          <pin id="pin02" class="pin02" />
          <pin id="pin01" class="pin01" />
          <pin id="pin00" class="pin00" />
        </pins-right>
        <pins-left>
          <pin id="pin10" class="pin10" />
          <pin id="pin11" class="pin11" />
          <pin id="pin12" class="pin12" />
          <pin id="pin13" class="pin13" />
          <pin id="pin14" class="pin14" />
        </pins-left>
        <pins-top>
          <pin id="pin09" class="pin09" />
          <pin id="pin08" class="pin08" />
          <pin id="pin07" class="pin07" />
          <pin id="pin06" class="pin06" />
          <pin id="pin05" class="pin05" />
        </pins-top>
        <pins-bottom>
          <pin id="pin15" class="pin15" />
          <pin id="pin16" class="pin16" />
          <pin id="pin17" class="pin17" />
          <pin id="pin18" class="pin18" />
          <pin id="pin19" class="pin19" />
        </pins-bottom>
      </pins>
    </chip>
  </chiprompt>
  <defs>
    <style type="text/css">
      .pin .active { fill: #e67206 }
    </style>
    <script type="text/javascript">
      <![CDATA[
      function update() {
        var currentTime = new Date();
        var secs = currentTime.getSeconds();
        getPin(secs % 20).classList.add('active');
        //document.querySelector('.chip .letter').classList.add('active');
        getPin((secs + 19) % 20).classList.remove('active');
      }
      function getPin(x) {
        var activeNum = x<10 ? ('0'+x) : x;
        return document.querySelector('.pin'+ activeNum);
      }
      setInterval(update, 100);
      ]]>
    </script>
  </defs>
</chaotikum-logo>

=== Chaotikum/chaotikum-logo/animated/chip-prompt-nbsp.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE chaotikum-logo SYSTEM "../chaotikum-logo.dtd">
<chaotikum-logo xmlns:svg="http://www.w3.org/2000/svg">
  <defs>
    <filter id="glow" height="150%" width="150%" filterUnits="userSpaceOnUse">
      <feGaussianBlur result="coloredBlur" stdDeviation="0.7" />
      <feOffset dx="0" dy="0" result="coloredBlur" />
      <feMerge> 
        <feMergeNode in="coloredBlur" />
        <feMergeNode in="SourceGraphic" /> 
      </feMerge>
    </filter>
    <style type="text/css">
      .chip { stroke: none }
      .pin { fill: #666 }
      .chip-body { fill: #1a1a1a }
      .prompt .underscore { fill:#b3b3b3; filter: url(#glow) }
      .prompt .prompt-start { fill:#b3b3b3 }
      .prompt .letter { display: none; }
      @-moz-keyframes blinking-cursor {
        0%   { opacity: 1; }
        35%  { opacity: 1; }
        50%  { opacity: 0; }
        85%  { opacity: 0; }
        100% { opacity: 1; }
      }
      @-webkit-keyframes blinking-cursor {
        0%   { opacity: 1; }
        35%  { opacity: 1; }
        50%  { opacity: 0; }
        85%  { opacity: 0; }
        100% { opacity: 1; }
      }
      .prompt .underscore {
        -webkit-animation: blinking-cursor 2.3s ease infinite;
        -moz-animation: blinking-cursor 2.3s ease infinite;
        animation: blinking-cursor 2.3s ease infinite;
      }
    </style>
  </defs>
  <chiprompt>
    <chip>
      <pins>
        <pins-right>
          <pin /><pin /><pin /><pin /><pin />
        </pins-right>
        <pins-left>
          <pin /><pin /><pin /><pin /><pin />
        </pins-left>
        <pins-top>
          <pin /><pin /><pin /><pin /><pin />
        </pins-top>
        <pins-bottom>
          <pin /><pin /><pin /><pin /><pin />
        </pins-bottom>
      </pins>
    </chip>
  </chiprompt>
</chaotikum-logo>
